# BiLSTM 모델 학습 설정

# 학습 하이퍼파라미터
epochs: 10
batch_size: 32
lr: 0.001
max_len: 256
patience: 3
num_workers: 0

# Vocabulary 설정
max_vocab_size: 20000
min_freq: 1

# 모델 하이퍼파라미터
model:
  embedding_dim: 128
  hidden_size: 128
  num_layers: 1
  dropout: 0.3

# 데이터 경로
data:
  train_path: "data/train.csv"
  val_path: "data/validation.csv"
  text_fields: ["title", "text"]

# 출력 설정
output:
  model_dir: "models"
  log_dir: "logs"

