# TextCNN 모델 학습 설정
epochs: 30
batch_size: 64
lr: 0.0008
max_len: 512
patience: 10
num_workers: 0

# Vocabulary
max_vocab_size: 30000
min_freq: 1

# Model
model:
  embedding_dim: 300
  filter_sizes: [2, 3, 4, 5]
  num_filters: 200
  dropout: 0.35

# 데이터 경로
data:
  train_path: "data/train.csv"
  val_path: "data/validation.csv"
  text_fields: ["title", "text"]

# 출력 설정
output:
  model_dir: "models"
  log_dir: "logs"
